#!/bin/sh

show_usage()
{
    echo "Usage: niagra [command]"
    echo "   commands:"
    echo "       start [-d] config_file     Start niagra instance with config file."
    echo "       list                       List running niagra instances."
    echo "       migrate [pid]              Migrate a niagra instance. Zero-downtime restart of all nodes."
    echo "       terminate [pid]            Terminate a niagra instance. Full-downtime kill of all nodes."
    echo "       state [pid]                Output state of existing niagra instance."
    echo "   options:"
    echo "       -d                         Debug mode. niagra instance will not be daemonized."
    echo "       pid                        pid of niagra instance. Not required if only one instance is executing."
    exit 1
}

command=$1
debug=0
config_file=""
pid=""

command_start()
{
    echo "start"
}


if [ $command = "start" ]; then
    if [ $2 = "-d" ]; then
        debug=1
        config_file=$3
    else
        config_file=$2
    fi
    if [ -z $config_file ]; then
        show_usage
    fi
    config_file=$2
    command_start

elif [ $command = "list" ]; then
    echo "listing"

elif [ $command = "migrate" ]; then
    echo "migrate"

elif [ $command = "terminate" ]; then
    echo "terminate"

elif [ $command = "state" ]; then
    echo "state"

else
    show_usage
fi